config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # users/show

  resources :users, only: [:show]

  resources :attractions, only: [:index, :show, :new, :destroy]
  resources :communities, only: [:destroy]
  resources :events, only: [:show, :destroy]
  resources :posts, only: [:show, :destroy]

  resources :favorite_categories, only: [:index]
  resources :event_categories, only: [:index]
  resources :favorite_events, only: [:index, :destroy]

  resources :categories do
    resources :favorite_categories, only: [:new, :create]
  end

  resources :events, only: [:show] do
    resources :favorite_events, only: [:new, :create]
    resources :categories, only: [:index] do
      resources :event_categories, only: [:new, :create]
    end
  end

  resources :cities do
    resources :events
    resources :posts
    resources :attractions
    resources :communities do
      resources :events
      resources :posts
    end
  end

  resources :events do
    post 'add_to_favorites', on: :member
    # get 'city_events', on: :collection
    # get 'favorite_events', on: :collection
  end

  resources :chatrooms, only: [:index, :new, :create, :show, :destroy] do
    resources :messages, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <%# <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
    ⬢ We love  <i class="fas fa-heart"></i> Culturecomb ⬢
    </div>
  </div> %>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    ⬢ Connecting Minds, Enriching Lives: CultureComb <i class="fas fa-heart"></i> Your Community, Your Connection ⬢
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'culture-comb.png', size: "40x40" %>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? # && current_user.admin? == false %>

          <li class="nav-item dropdown">
            <%= link_to "Chat", chatrooms_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          	<%= link_to "Cities", cities_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <span class="nav-link"><%= current_user.first_name %></span>
          </li>

          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.present? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
              <% else %>
                <%= image_tag ("admin.png"), class: "avatar", alt: "dropdown menu" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if current_user.admin? %>

                <%= link_to "Add City", new_city_path, class: "dropdown-item" %>
                <%# <%=link_to "All Attractions", attractions_path, class: "dropdown-item" %>
                <%# <%=link_to "All Communities","#" , class: "dropdown-item"%>
                <%#link_to "Add new community", new_city_community_path , class: "dropdown-item"%>
                <%# link_to "Add new attraction", new_attraction_path, class: "dropdown-item" %>
              <% else %>
              <!--
                <%= link_to "All Cities", cities_path, class: "dropdown-item" %>
                <%= link_to "All Attractions", attractions_path, class: "dropdown-item" %>
                <%= link_to "All Communities", "#", class: "dropdown-item" %> -->
              <% end %>

                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Join now ⬢", new_user_registration_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Login ⬢", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>