config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # users/show

  resources :users, only: [:show]

  resources :attractions, only: [:index, :show, :new, :destroy]
  resources :communities, only: [:destroy]
  resources :events, only: [:show, :destroy]
  resources :posts, only: [:show, :destroy]

  resources :favorite_categories, only: [:index]
  resources :event_categories, only: [:index]
  resources :favorite_events, only: [:index, :destroy]

  resources :categories do
    resources :favorite_categories, only: [:new, :create]
  end

  resources :events, only: [:show] do
    resources :favorite_events, only: [:new, :create]
    resources :categories, only: [:index] do
      resources :event_categories, only: [:new, :create]
    end
  end

  resources :cities do
    resources :events
    resources :posts
    resources :attractions
    resources :communities do
      resources :events
      resources :posts
    end
  end

  resources :events do
    post 'add_to_favorites', on: :member
    # get 'city_events', on: :collection
    # get 'favorite_events', on: :collection
  end

  resources :chatrooms, only: [:index, :new, :create, :show, :destroy] do
    resources :messages, only: :create
  end
end

app/models/event.rb
class Event < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :city
  belongs_to :community, optional: true
  belongs_to :user
  has_many :event_categories
  has_many :categories, through: :event_categories
  has_many :favorite_events, dependent: :destroy

  has_many_attached :photos

  validates :name, :website_url, :description, :address, :date, presence: true
  validates :photos, presence: true

  validates :description, length: { minimum: 10 }
  # validates :date
  # , date: true
  validate :event_date_cannot_be_in_the_past

  include PgSearch::Model

  pg_search_scope :search_by_community,
    against: [ :name ],
    associated_against: {
      community: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
    }

  private

  def event_date_cannot_be_in_the_past
    if date.present? && date < Date.today
      errors.add(:date, "can't be in the past")
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :destroy, :edit, :update]

  def index
    @city = City.find(params[:city_id])
    @events = @city.events
    if params[:query].present?
      @events = Event.search_by_community(params[:query])
    end

    @markers = @events.geocoded.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { event: event}),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def show
    if params[:city_id].present?
      @city = City.find(params[:city_id])
    elsif params[:community_id].present?
      @community = Community.find(params[:community_id])
    end
    # @array_event = [@event]
    @markers = @event.geocode.map do |event|
      {
        lat: @event.latitude,
        lng: @event.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { event: @event}),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def new
    if params[:community_id].present?
      @city = City.find(params[:city_id])
      @community = Community.find(params[:community_id])
    else params[:city_id].present?
      @city = City.find(params[:city_id])
    end
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if params[:community_id].present?
      @city = City.find(params[:city_id])
      @community = Community.find(params[:community_id])
      @event.community = @community
      @event.city = @city
      @event.save!
      redirect_to city_community_path(@city, @community)
    else params[:city_id].present?
      @city = City.find(params[:city_id])
      @event.city = @city
      @event.save!
      redirect_to city_events_path
    end
  end

  def edit
    @city = City.find(params[:city_id])
    @event = @city.events.find(params[:id])
  end

  def update
    @city = City.find(params[:city_id])
    @event = @city.events.find(params[:id])
    if @event.update(event_params)
      redirect_to city_events_path
    else
      render :edit
    end
  end

  def destroy
    @event.destroy

    redirect_to city_events_path(@event)
  end

  def add_to_favorites
    @event = Event.find(params[:id])
    @favorite_event = FavoriteEvent.new(event: @event)
    @favorite_event.user = current_user

    if @favorite_event.save!
      redirect_to favorite_events_path, notice: 'Event added to favorites.'
    else
      redirect_to events_path, alert: 'Unable to add event to favorites.'
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :website_url, :date, :address,
                                  :phone_number, :start_time, photos: [])
  end
end

app/views/events/_city_events.html.erb
<!-- app/views/events/all.html.erb -->
<h1>All Events</h1>
<%= render partial: 'city_events', locals: { events: @events } %>
<!-- Other content -->

app/views/events/_favorite_events.html.erb
<!-- app/views/events/favorites.html.erb -->
<h1>Favorite Events</h1>
<%= render partial: 'favorite_events', locals: { events: @events } %>
<!-- Other content -->

app/views/events/_info_window.html.erb
<h2><%= event.name %></h2>
<p><%= event.address %></p>

app/views/events/_marker.html.erb
<%= image_tag "map_pin.png", height: 30, width: 30, alt: "map_pin" %>

app/views/events/edit.html.erb
<div class="edit-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),
        url('<%= cl_image_path(@city.photo.key) %>');">
  <div class="container">
    <div class="edit-form-heading mt-3">
      <h3>Revamp Your Event: Ignite Excitement!</h3>
    </div>
    <%= simple_form_for([@city, @event], html: { class: "edit-form" }) do |f|%>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :website_url %>
      <%= f.input :date , label: "Event Date" %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :start_time %>
      <%= f.input :photos , label: "Upload Images", as: :file, input_html: { multiple: true } %>
      <%= f.button :submit, "Update event", class: "btn btn-primary w-100 edit-form-submit"%>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="index">
  <div class="row">
    <div class="col-12 col-lg-9 border events-left">
      <div class="events-heading border mt-3">
        <h3>Eventopia: Unleash the Experience</h3>
      </div>

      <div class="row justify-content-center">
        <div class="col-sm-8 my-3">
          <%= form_with url: city_events_path(@city), method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Type a keyword"
              %>
            <%= submit_tag "Search", name: "", class: "btn btn-secondary" %>
          <% end %>
        </div>
      </div>

      <div class="cards">
      <% @events.each do |event| %>
        <div class="card" >
          <% if event.photos.any? %>
            <%= link_to city_event_path(@city, event) do %>
              <%= cl_image_tag event.photos.last.key, class: "card-img-top event-card-img", alt: event.name %>
            <% end %>
          <% else %>
            <!-- Display a placeholder image or default image if no photos are available -->
          <%= image_tag "placeholder.jpg", class: "card-img-top", alt: "Placeholder Image" %>
          <% end %>

          <div class="card-body">
            <h5 class="card-title"><%= event.name %></h5>
            <p class="card-text"><i class="fa-solid fa-location-dot"></i> <%= event.address %></p>
          </div>

          <div class="icon-actions">
            <%= button_to add_to_favorites_event_path(event), method: :post do %>
              <i class="fa-solid fa-heart-circle-plus"></i>
            <% end %>
            <%= button_to edit_city_event_path(@city, event), method: :get do %>
              <i class="fa-solid fa-pen-to-square"></i>
            <% end %>
            <%= button_to event_path(event), method: :delete do %>
              <i class="fa-solid fa-trash-can"></i>
            <% end %>

          </div>
        </div>
      <% end %>
    </div>

    </div>

    <div class="col-12 col-lg-3 border events-right">
      <div class="event-options">
        <div class="favorite-events border">
          <h5>Discover Your Event Favorites. Dive In!</h5>
          <i class="fa-brands fa-gratipay fa-beat"></i></i> <%= link_to 'My Favorite Events', favorite_events_path %>
        </div>
        <div class="new-event border">
          <h5>Expand the Excitement: Add a New Event to the Lineup!</h5>
          <i class="fa-regular fa-square-plus fa-beat"></i></i> <%= link_to 'Add New Event', new_city_event_path %>
        </div>
      </div>

      <div class="city-info border">
        <%= link_to city_path(@city) do %>
          <%= cl_image_tag @city.photo.key, class: "card-img-top", alt: @city.name %>
        <% end %>
        <div class="city-name-description">
          <h5><%= @city.name %></h5>
          <p><%= @city.description %></p>
        </div>
      </div>

    </div>
  </div>
</div>
</div>

app/views/events/new.html.erb
<div class="edit-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),
        url('<%= cl_image_path(@city.photo.key) %>');">
  <div class="container-form" >
   <div class="row">
      <div class="col-12 col-lg-6" id="description" style="margin-top: 100px;">
        <h1 style="color:white; margin:0px;">  Put your event in the spotlight! Add it to our platform and captivate audiences with a memorable experience <span style="color: #FFD369; font-weight: bolder">So what are you waiting for? Start creating your event today!</span></h1>
      </div>
      <div class="col-12 col-lg-6" id="form" style="padding-left: 50px;" >
        <div class="container border mb-5 p-4 add-event">
          <%= simple_form_for([@city,@community,@event], html: { class: "new-form" }) do |f|%>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :website_url %>
            <%= f.input :date, label:"Event Date", start_year: Time.current.year %>
            <%= f.input :address %>
            <%= f.input :phone_number %>
            <%= f.input :start_time %>
            <%= f.input :photos, label: "Upload Images", as: :file, input_html: { multiple: true } %>
            <%= f.button :submit, "Add event", class: "btn btn-primary w-100 new-form-submit"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<div>

app/views/events/show.html.erb
<div class="container show-form" style="max-width: 50%">
    <div class="row">
      <div class="show-form-heading">
        <h3>Event Unwrapped: Explore the Details!</h3>
      </div>
    </div>
    <div class="row">
      <% @event.photos.each_slice(1).with_index do |events_slice, index| %>
        <% events_slice.each do |event| %>
          <%= cl_image_tag event.key, class:"show-form-img", alt: event.name %>
        <% end %>
      <% end %>
    </div>
    <div class="row">
      <div class="col-12 col-lg-9">
        <div class="border-bottom mt-3 mb-3">
          <h3 class="name-show mt-3"><%= @event.name %></h3>
          <h5 class="info-show"> <i class="fa-solid fa-location-dot"></i> <%= @event.address %> </h5>
          <p class="info-show"> <i class="fa-solid fa-calendar-days"></i> <%= @event.date %>  </p>
          <p class="info-show"><i class="fa-solid fa-clock"></i> <%= @event.start_time %></p>
        </div>
      </div>
      <div class="col-12 col-lg-3">
        <div class="dive-back border">
          <h5>Want to Explore more?</h5>
          <i class="fa-regular fa-hand-point-left fa-beat"></i> <%= link_to "Dive Back!", city_events_path(@city) %>
        </div>
      </div>
      <div class="border-bottom mt-2 mb-3">
        <p class="info-show"><i class="fa-regular fa-rectangle-list"></i> <%= @event.description %></p>
      </div>
      <div class="border-bottom mt-2 mb-3">
        <h6 class="description-show">Discover More!</h6>
        <a class="info-show" href="<%= @event.website_url %>"><i class="fa-solid fa-link"></i> <%= @event.website_url %></a>
      </div>
      <div class="border-bottom mt-2 mb-3">
        <h6 class="description-show">Let's Stay Connected!</h6>
        <p class="info-show"><i class="fa-solid fa-square-phone"></i> <%= @event.phone_number %></p>
      </div>


    </div>
    <div class="row show-map-section">
      <h6 class="map-heading">Find Your Way to the Event!</h6>
      <div class="container">
        <div class="map-show"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY']%>">
        </div>
      </div>
    </div>
  </div>
</div>