config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # users/show

  resources :users, only: [:show]

  resources :attractions, only: [:index, :show, :new, :destroy]
  resources :communities, only: [:destroy]
  resources :events, only: [:show, :destroy]
  resources :posts, only: [:show, :destroy]

  resources :favorite_categories, only: [:index]
  resources :event_categories, only: [:index]
  resources :favorite_events, only: [:index, :destroy]

  resources :categories do
    resources :favorite_categories, only: [:new, :create]
  end

  resources :events, only: [:show] do
    resources :favorite_events, only: [:new, :create]
    resources :categories, only: [:index] do
      resources :event_categories, only: [:new, :create]
    end
  end

  resources :cities do
    resources :events
    resources :posts
    resources :attractions
    resources :communities do
      resources :events
      resources :posts
    end
  end

  resources :events do
    post 'add_to_favorites', on: :member
    # get 'city_events', on: :collection
    # get 'favorite_events', on: :collection
  end

  resources :chatrooms, only: [:index, :new, :create, :show, :destroy] do
    resources :messages, only: :create
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :city
  belongs_to :community

  validates :title, :website_url, :content, presence: true
  validates :photo, presence: true

  has_one_attached :photo
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :destroy, :edit, :update]

  def index
    @city = City.find(params[:city_id])
    @posts = @city.posts
    @community = Community.find(params[:community_id])
    @post = Post.new
  end

  def show
    @city = City.find(params[:city_id])
    @community = Community.find(params[:community_id])
    @posts = @city.posts
  end

  def new
    @post = Post.new
    @city = City.find(params[:city_id])
    @community = Community.find(params[:community_id])
    @posts = @city.posts
  end

  def create
    @city = City.find(params[:city_id])
    @post = Post.new(post_params)
    @post.city = @city
    @post.user = current_user
    if params[:community_id].present?
      @community = Community.find(params[:community_id])
      @post.community = @community
      @post.save!
      redirect_to city_community_posts_path(@city, @community)
    else
      @post.save!
      redirect_to city_posts_path
    end
  end

  def edit
    @city = City.find(params[:city_id])
    @post = @city.posts.find(params[:id])
  end

  def update
    @city = City.find(params[:city_id])
    @post = @city.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to city_posts_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy

    redirect_to city_posts_path(@post)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :website_url, :photo)
  end
end

app/views/posts/_new.html.erb
<%= simple_form_for([@city,@community,@post], html: { class: "new-form" }) do |f|%>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :website_url %>
  <%= f.input :photo, label: "Upload Image", as: :file %>
  <%= f.button :submit, "Add post", class: "btn btn-primary w-100 new-form-submit"%>
<% end %>

app/views/posts/edit.html.erb
<div class="edit-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),
        url('<%= cl_image_path(@city.photo.key) %>');">
  <div class="container">
    <div class="edit-form-heading mt-3">
      <h3>Revamp and Engage: Edit Your Post!</h3>
    </div>
    <%= simple_form_for([@city, @post], html: { class: "edit-form" }) do |f|%>
      <%= f.input :title %>
      <%= f.input :content %>
      <%= f.input :website_url %>
      <%= f.input :photo, label: "Upload Image", as: :file %>
      <%= f.button :submit, "Update post", class: "btn btn-primary w-100 edit-form-submit"%>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="index">
  <div class="row">
    <div class="col-12 col-lg-9 border events-left">
      <div class="events-heading border mt-3">
        <h3>Unveiling All Posts</h3>
      </div>

      <div class="cards">
        <% @posts.each do |post| %>
          <div class="card" >
            <% if post.photo.present? %>
              <%= link_to city_community_post_path(@city, @community, post) do %>
                <%= cl_image_tag post.photo.key, class: "card-img-top event-card-img", alt: post.title %>
              <% end %>
            <% else %>
              <!-- Display a placeholder image or default image if no photos are available -->
            <%= image_tag "placeholder.jpg", class: "card-img-top", alt: "Placeholder Image" %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= post.title %></h5>
            </div>

            <div class="icon-actions">
              <a href=<%= edit_city_post_path(@city, post) %>><i class="fa-solid fa-pen-to-square"></i></a>
              <%= link_to post_path(post),
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                class: "delete-rs-button" do %>
                <i class="fa-solid fa-trash-can"></i>
              <% end %>
            </div>

          </div>
        <% end %>
      </div>

    </div>

    <div class="col-12 col-lg-3 border events-right">
      <div class="event-options">
        <div class="favorite-events border">
          <h5>Expand the Excitement: Add a New Post to the Lineup!</h5>
          <%= render "new" %>
        </div>
        <div class="new-event border">
          <h5>Ready to Chat? Share Your Ideas!</h5>
          <i class="fa-solid fa-comments fa-beat"></i> <%= link_to 'Start Conversation', chatrooms_path %>
        </div>
      </div>

      <div class="city-info border">
        <%= link_to city_community_path(@city, @community) do %>
          <%= cl_image_tag @city.photo.key, class: "card-img-top", alt: @city.name %>
        <% end %>
        <div class="city-name-description">
          <h5 style="color: rgb(6, 128, 128);">Return to the Community Hub  <i class="fa-regular fa-hand-point-up fa-beat"></i></h5>
        </div>
      </div>

    </div>
  </div>
</div>
</div>

app/views/posts/new.html.erb
<div class="container">
<h1>Post New Page</h1>
<%= simple_form_for([@city,@community,@post], html: { class: "new-form" }) do |f|%>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :website_url %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, "Add post", class: "btn btn-primary w-100 new-form-submit"%>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="container show-form" style="max-width: 50%">
    <div class="row">
      <div class="show-form-heading">
        <h3>Post Unwrapped: Explore the Details!</h3>
      </div>
    </div>
    <div class="row">
      <%= cl_image_tag @post.photo.key, class: "show-form-img", alt: @post.title %>
    </div>
    <div class="row">
      <div class="col-12 col-lg-9">
        <div class="border-bottom mt-3 mb-3">
          <h3 class="name-show mt-3"><%= @post.title %></h3>
          <p class="info-show"><i class="fa-regular fa-rectangle-list"></i> <%= @post.content %></p>
        </div>
      </div>
      <div class="col-12 col-lg-3">
        <div class="dive-back border">
          <h5>Want to Explore more?</h5>
          <i class="fa-regular fa-hand-point-left fa-beat"></i> <%= link_to "Dive Back", city_community_path(@city, @community) %>
        </div>
      </div>
      <div class="border-bottom mt-2 mb-3">
        <h6 class="description-show">Discover More!</h6>
        <a class="info-show" href="<%= @post.website_url %>"><i class="fa-solid fa-link"></i> <%= @post.website_url %></a>
      </div>

    </div>
    <div class="row show-map-section">
    <h6 class="map-heading"> Explore the Post's Location!</h6>
      <div class="container">
        <div class="map-show"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY']%>">
        </div>
      </div>
    </div>
  </div>
</div>