config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # users/show

  resources :users, only: [:show]

  resources :attractions, only: [:index, :show, :new, :destroy]
  resources :communities, only: [:destroy]
  resources :events, only: [:show, :destroy]
  resources :posts, only: [:show, :destroy]

  resources :favorite_categories, only: [:index]
  resources :event_categories, only: [:index]
  resources :favorite_events, only: [:index, :destroy]

  resources :categories do
    resources :favorite_categories, only: [:new, :create]
  end

  resources :events, only: [:show] do
    resources :favorite_events, only: [:new, :create]
    resources :categories, only: [:index] do
      resources :event_categories, only: [:new, :create]
    end
  end

  resources :cities do
    resources :events
    resources :posts
    resources :attractions
    resources :communities do
      resources :events
      resources :posts
    end
  end

  resources :events do
    post 'add_to_favorites', on: :member
    # get 'city_events', on: :collection
    # get 'favorite_events', on: :collection
  end

  resources :chatrooms, only: [:index, :new, :create, :show, :destroy] do
    resources :messages, only: :create
  end
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :city
  belongs_to :user
  has_many :events
  has_many :posts

  validates :name, :description, presence: true
  validates :description, length: { minimum: 10 }
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :destroy, :edit, :update]

  def index
    @city = City.find(params[:city_id])
    @communities = @city.communities
  end

  def show
    @city = City.find(params[:city_id])
    @community = @city.communities.find(params[:id])
    @events = @community.events
    @posts = @community.posts
  end

  def new
    @city = City.find(params[:city_id])
    @community = Community.new
  end

  def create
    @city = City.find(params[:city_id])

    @community = Community.new(community_params)
    @community.city = @city
    @community.user = current_user
    @community.save!

    redirect_to city_communities_path
  end

  def edit
    @city = City.find(params[:city_id])
    @community = @city.communities.find(params[:id])
  end

  def update
    @city = City.find(params[:city_id])
    @community = @city.communities.find(params[:id])
    if @community.update(community_params)
      redirect_to city_communities_path
    else
      render :edit
    end
  end

  def destroy
    @community.destroy
    redirect_to city_communities_path(@community)
  end

  private

  def set_community
    @community = Community.find(params[:id])
  end

  def community_params
    params.require(:community).permit(:name, :description)
  end
end

app/views/communities/edit.html.erb
<div class="container">
  <h1>Community Edit Page</h1>
  <%= simple_form_for([@city, @community], html: { class: "new-form" }) do |f|%>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.button :submit, "Update community", class: "btn btn-primary"%>
  <% end %>
</div>

app/views/communities/index.html.erb
<div class="index-renting-space">
  <div class="container">
    <h1 style="text-align: center;">All Communities</h1>
    <div class="row">
      <div class="cards">
        <% @communities.each do |community| %>
          <div class="card">
            <%= link_to city_community_path(@city, community) do %>
              <div class="card-body">
                <h5 class="card-title"><%= community.name %></h5>
                <p class="card-text mb-1"><%= community.description %></p>
              </div>
            <% end %>
            <% if current_user.admin? %>
              <a href=<%= edit_city_community_path(@city, community) %> class="btn btn-secondary">Update Community</a>
              <a href=<%= community_path(community) %> class="btn btn-danger">Delete Community</a>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/communities/new.html.erb
<h1>Community New Page</h1>
<%= simple_form_for([@city, @community], html: { class: "new-form" }) do |f|%>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.button :submit, "Add community", class: "btn btn-primary w-100 new-form-submit"%>
<% end %>

app/views/communities/show.html.erb
<div class="community-show">
  <%# Banner section %>
  <div class="community-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path(@city.photo.key) %>');">
    <div class="container">
      <h1><%= @community.name + " community in " + @city.name %></h1>
      <p><%= @community.description %></p>
    </div>
  </div>

  <%# Posts section %>
  <div class="community-posts border-bottom">
    <div class="container">
      <h1>Exploring New Horizons</h1>
      <% @posts.each do |post| %>
        <div class="card mb-3 m-auto community-posts-card">
          <div class="row no-gutters">
            <div class="col-sm-4">
              <% if post.photo.present? %>
                <%= link_to city_community_post_path(@city, @community, post) do %>
                  <div class="card-img-wrapper">
                    <%= cl_image_tag post.photo.key, class: "card-img rounded", alt: post.title %>
                  </div>
                <% end %>
              <% else %>
                <%= image_tag "placeholder.jpg", class: "card-img", alt: "Placeholder Image" %>
              <% end %>
            </div>
            <div class="col-md-8">
              <div class="card-body text-left py-6">
                <h4 class="card-title"><%= post.title %></h4>
                <p class="card-text"><%= post.content %></p>
                <p class="post-creator"><%= post.user.username %> , <%= Post.last.created_at.strftime("%a, %d %b %Y") %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <div class="gap-2 col-6 justify-content-center text-center mx-auto mt-3 community-post">
        <%= link_to "Discover All Posts in One Place", city_community_posts_path(@city, @community), class: "posts-all" %> <i class="fa-solid fa-angles-right fa-beat"></i>
      </div>
    </div>
  </div>

  <%# Events section %>
  <div class="community-events">
    <h1>Events for Networking</h1>
    <div class="container">
      <div class="row">
        <% @events.first(2).each do |event| %>
          <div class="col-sm-6 mb-3 community-column">
            <div class="card community-event-card">
              <% if event.photos.any? %>
                <%= link_to city_community_event_path(@city,@community,event) do %>
                  <%= cl_image_tag event.photos.last.key, class: "img-fluid rounded", alt: event.name %>
                <% end %>
              <% else %>
                <%= image_tag "placeholder.jpg", class: "card-img-top", alt: "Placeholder Image" %>
              <% end %>
              <div class="card-body">
                <h4 class="card-title"><%= event.name %></h3>
                <p class="card-text"><i class="fa-solid fa-location-dot"></i> <%= event.address %></p>
                <p class="card-text"><i class="fa-solid fa-calendar-week"></i> <%= event.date %></p>
                <p class="card-text"><i class="fa-solid fa-clock"></i> <%= event.start_time.strftime("%H:%M") %></p>
              </div>
              <% if current_user.admin? %>
                <div class="card-footer">
                  <%= link_to "Update Event", edit_city_event_path(@city, event), class: "btn btn-secondary" %>
                  <%= link_to "Delete Event", event_path(event), class: "btn btn-danger" %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="gap-2 col-6 justify-content-center text-center mx-auto mt-3 community-event">
        <%= link_to "Uncover the Diversity of Events", city_events_path(@city), class: "events-all" %> <i class="fa-solid fa-angles-right fa-beat"></i>
      </div>
    </div>
  </div>
</div>